future: false
permalink: /:year/:month/:title
markdown: kramdown
highlighter: none
website: "https://ryanbigg.com"
plugins:
  - jekyll-feed
site:
  url: "https://ryanbigg.com"
sass:
  sass_dir: _sass
